
import { College } from './types';

export const INITIAL_COLLEGES: College[] = [
  // --- RIO DE JANEIRO (RJ) - NOVO LEVANTAMENTO ---
  { id: 'rj-ufrj-cap', name: 'UFRJ - Univ. Federal do Rio de Janeiro', city: 'Rio de Janeiro', state: 'RJ', address: 'Av. Pedro Calmon, 550, Cidade Universitária', type: 'Federal', phone: '(21) 3938-9600', website: 'ufrj.br', courses: ['Bioquímica', 'Biomedicina', 'Farmácia', 'Enfermagem', 'Medicina', 'Biotecnologia'], createdAt: 1740000000400 },
  { id: 'rj-uerj-cap', name: 'UERJ - Univ. do Estado do Rio de Janeiro', city: 'Rio de Janeiro', state: 'RJ', address: 'Rua São Francisco Xavier, 524, Maracanã', type: 'Estadual', phone: '(21) 2334-0000', website: 'uerj.br', courses: ['Enfermagem', 'Medicina', 'Biologia', 'Nutrição'], createdAt: 1740000000401 },
  { id: 'rj-unirio-cap', name: 'UNIRIO - Univ. Federal do Estado do RJ', city: 'Rio de Janeiro', state: 'RJ', address: 'Av. Pasteur, 296, Urca', type: 'Federal', phone: '(21) 2542-4450', website: 'unirio.br', courses: ['Biomedicina', 'Enfermagem', 'Medicina', 'Biologia'], createdAt: 1740000000402 },
  { id: 'rj-uva-cap', name: 'UVA (Veiga de Almeida)', city: 'Rio de Janeiro', state: 'RJ', address: 'Rua Ibituruna, 108, Maracanã', type: 'Privada', phone: '(21) 2574-8888', website: 'uva.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia', 'Medicina'], createdAt: 1740000000403 },
  { id: 'rj-puc-cap', name: 'PUC-Rio', city: 'Rio de Janeiro', state: 'RJ', address: 'Rua Marquês de São Vicente, 225, Gávea', type: 'Privada', phone: '(21) 3527-1001', website: 'puc-rio.br', courses: ['Ciências Biológicas (Base Bioquímica)'], createdAt: 1740000000404 },
  { id: 'rj-unesa-cap', name: 'UNESA (Estácio)', city: 'Rio de Janeiro', state: 'RJ', address: 'Rua Riachuelo, 27, Lapa', type: 'Privada', phone: '0800 880 6767', website: 'estacio.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia', 'Medicina'], createdAt: 1740000000405 },
  { id: 'rj-unigran-cap', name: 'UNIGRANRIO', city: 'Rio de Janeiro', state: 'RJ', address: 'Rua Lapa, 86, Centro', type: 'Privada', phone: '(21) 3219-4040', website: 'unigranrio.com.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia', 'Medicina'], createdAt: 1740000000406 },
  { id: 'rj-ibmr-cap', name: 'IBMR', city: 'Rio de Janeiro', state: 'RJ', address: 'Av. das Américas, 2603, Barra da Tijuca', type: 'Privada', phone: '(21) 3544-1137', website: 'ibmr.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia'], createdAt: 1740000000407 },
  { id: 'rj-souza-cap', name: 'Souza Marques', city: 'Rio de Janeiro', state: 'RJ', address: 'Av. Ernani Cardoso, 335, Cascadura', type: 'Privada', phone: '(21) 2127-3100', website: 'souzamarques.br', courses: ['Enfermagem', 'Medicina', 'Biologia'], createdAt: 1740000000408 },
  { id: 'rj-uff-nit', name: 'UFF - Univ. Federal Fluminense', city: 'Niterói', state: 'RJ', address: 'Rua Miguel de Frias, 9, Icaraí', type: 'Federal', phone: '(21) 2629-5000', website: 'uff.br', courses: ['Biomedicina', 'Farmácia', 'Enfermagem', 'Medicina', 'Biologia'], createdAt: 1740000000409 },
  { id: 'rj-unipli-nit', name: 'UNIPLI (Anhanguera)', city: 'Niterói', state: 'RJ', address: 'Av. Visconde do Rio Branco, 123', type: 'Privada', phone: '(21) 2109-2900', website: 'anhanguera.com', courses: ['Enfermagem', 'Biomedicina'], createdAt: 1740000000410 },
  { id: 'rj-uerj-sg', name: 'UERJ (FFP)', city: 'São Gonçalo', state: 'RJ', address: 'Rua Dr. Francisco Portela, 1470', type: 'Estadual', phone: '(21) 3705-2227', website: 'uerj.br', courses: ['Ciências Biológicas'], createdAt: 1740000000411 },
  { id: 'rj-unigran-dc', name: 'UNIGRANRIO (Sede)', city: 'Duque de Caxias', state: 'RJ', address: 'Rua Prof. José de Souza Herdy, 1160', type: 'Privada', phone: '(21) 2672-7700', website: 'unigranrio.com.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia', 'Medicina'], createdAt: 1740000000412 },
  { id: 'rj-ufrj-xe', name: 'UFRJ (Xerém)', city: 'Duque de Caxias', state: 'RJ', address: 'Estrada de Xerém, 27', type: 'Federal', phone: '(21) 2679-1313', website: 'xerem.ufrj.br', courses: ['Biotecnologia', 'Nanotecnologia', 'Biofísica'], createdAt: 1740000000413 },
  { id: 'rj-ufrrj-ni', name: 'UFRRJ (Nova Iguaçu)', city: 'Nova Iguaçu', state: 'RJ', address: 'Av. Governador Roberto Silveira, s/n', type: 'Federal', phone: '(21) 2669-0105', website: 'institucional.ufrrj.br', courses: ['Biologia'], createdAt: 1740000000414 },
  { id: 'rj-unig-ni', name: 'UNIG', city: 'Nova Iguaçu', state: 'RJ', address: 'Av. Abílio Augusto Távora, 2134', type: 'Privada', phone: '(21) 2765-4000', website: 'unig.br', courses: ['Medicina', 'Enfermagem', 'Farmácia'], createdAt: 1740000000415 },
  { id: 'rj-ifrj-nil', name: 'IFRJ (Nilópolis)', city: 'Nilópolis', state: 'RJ', address: 'Rua Lúcio Tavares, 1045', type: 'Federal', phone: '(21) 2691-9800', website: 'portal.ifrj.edu.br', courses: ['Farmácia', 'Química (Bioquímica)'], createdAt: 1740000000416 },
  { id: 'rj-fmp-pet', name: 'FMP (Faculdade de Medicina de Petrópolis)', city: 'Petrópolis', state: 'RJ', address: 'Rua Machado Fagundes, 326', type: 'Privada', phone: '(24) 2244-6464', website: 'fmp.fase.edu.br', courses: ['Medicina', 'Enfermagem'], createdAt: 1740000000417 },
  { id: 'rj-ucp-pet', name: 'UCP (Petrópolis)', city: 'Petrópolis', state: 'RJ', address: 'Rua Benjamin Constant, 213', type: 'Privada', phone: '(24) 2244-4000', website: 'ucp.br', courses: ['Biomedicina', 'Enfermagem'], createdAt: 1740000000418 },
  { id: 'rj-unifeso-ter', name: 'UNIFESO', city: 'Teresópolis', state: 'RJ', address: 'Av. Alberto Torres, 111', type: 'Privada', phone: '(21) 2641-7000', website: 'unifeso.edu.br', courses: ['Medicina', 'Enfermagem', 'Farmácia', 'Biologia'], createdAt: 1740000000419 },
  { id: 'rj-uff-fri', name: 'UFF (Nova Friburgo)', city: 'Nova Friburgo', state: 'RJ', address: 'Rua Dr. Silvio Henrique Braune, 22', type: 'Federal', phone: '(22) 2528-7168', website: 'uff.br', courses: ['Biomedicina', 'Odontologia'], createdAt: 1740000000420 },
  { id: 'rj-ufrj-cf', name: 'UFRJ (Cabo Frio)', city: 'Cabo Frio', state: 'RJ', address: 'Estrada de Perynas, s/n', type: 'Federal', phone: '(22) 2643-2234', website: 'ufrj.br', courses: ['Medicina', 'Biologia Marinha'], createdAt: 1740000000421 },
  { id: 'rj-unilagos-cf', name: 'UNILAGOS', city: 'Cabo Frio', state: 'RJ', address: 'Rua Jorge Lóssio, 250', type: 'Privada', phone: '(22) 2647-6400', website: 'unilagos.edu.br', courses: ['Enfermagem', 'Farmácia', 'Biomedicina'], createdAt: 1740000000422 },
  { id: 'rj-uenf-cam', name: 'UENF - Univ. Estadual do Norte Fluminense', city: 'Campos dos Goytazes', state: 'RJ', address: 'Av. Alberto Lamego, 2000', type: 'Estadual', phone: '(22) 2739-7000', website: 'uenf.br', courses: ['Biologia', 'Biotecnologia'], createdAt: 1740000000423 },
  { id: 'rj-uff-cam', name: 'UFF (Campos)', city: 'Campos dos Goytazes', state: 'RJ', address: 'Rua José do Patrocínio, 71', type: 'Federal', phone: '(22) 2733-0310', website: 'uff.br', courses: ['Biologia', 'Enfermagem'], createdAt: 1740000000424 },
  { id: 'rj-fmc-cam', name: 'FMC (Faculdade de Medicina de Campos)', city: 'Campos dos Goytazes', state: 'RJ', address: 'Av. Alberto Torres, 217', type: 'Privada', phone: '(22) 2101-1200', website: 'fmc.br', courses: ['Medicina', 'Farmácia'], createdAt: 1740000000425 },
  { id: 'rj-unig-ita', name: 'UNIG (Itaperuna)', city: 'Itaperuna', state: 'RJ', address: 'BR 356, km 2', type: 'Privada', phone: '(22) 3821-3400', website: 'unig.br', courses: ['Medicina', 'Enfermagem', 'Farmácia'], createdAt: 1740000000426 },
  { id: 'rj-uff-vr', name: 'UFF (Volta Redonda)', city: 'Volta Redonda', state: 'RJ', address: 'Rua Desembargador Ellis Hermydio Figueira, 783', type: 'Federal', phone: '(24) 2107-3700', website: 'uff.br', courses: ['Biociências'], createdAt: 1740000000427 },
  { id: 'rj-unifoa-vr', name: 'UniFOA', city: 'Volta Redonda', state: 'RJ', address: 'Av. Paulo Erlei Alves Abrantes, 1325', type: 'Privada', phone: '(24) 3340-8400', website: 'unifoa.edu.br', courses: ['Medicina', 'Enfermagem', 'Farmácia', 'Biologia'], createdAt: 1740000000428 },
  { id: 'rj-vassouras-vas', name: 'Universidade de Vassouras', city: 'Vassouras', state: 'RJ', address: 'Av. Expedicionário Oswaldo de Almeida Ramos, 280', type: 'Privada', phone: '(24) 2471-8388', website: 'universidadedevassouras.edu.br', courses: ['Medicina', 'Enfermagem', 'Farmácia', 'Biomedicina'], createdAt: 1740000000429 },
  { id: 'rj-unifaa-val', name: 'UNIFAA', city: 'Valença', state: 'RJ', address: 'Rua Sargento Vitor Hugo, 161', type: 'Privada', phone: '(24) 2453-0700', website: 'unifaa.edu.br', courses: ['Medicina', 'Enfermagem', 'Farmácia'], createdAt: 1740000000430 },

  // --- BAHIA (BA) - MANTIDOS ---
  { id: 'ba-ufba-salvador', name: 'UFBA - Universidade Federal da Bahia', city: 'Salvador', state: 'BA', address: 'Rua Augusto Viana, s/n, Canela', type: 'Federal', phone: '(71) 3283-7070', website: 'ufba.br', courses: ['Bioquímica', 'Biomedicina', 'Farmácia', 'Enfermagem', 'Medicina', 'Biologia'], createdAt: 1740000000300 },
  { id: 'ba-uneb-salvador', name: 'UNEB - Universidade do Estado da Bahia', city: 'Salvador', state: 'BA', address: 'Rua Silveira Martins, 2555, Cabula', type: 'Estadual', phone: '(71) 3117-2200', website: 'uneb.br', courses: ['Enfermagem', 'Farmácia', 'Medicina', 'Biologia'], createdAt: 1740000000302 },
  { id: 'ba-uesb-conquista', name: 'UESB - Univ. Estadual do Sudoeste da Bahia', city: 'Vitória da Conquista', state: 'BA', address: 'Estrada do Bem Querer, km 4', type: 'Estadual', phone: '(77) 3424-8600', website: 'uesb.br', courses: ['Farmácia', 'Enfermagem', 'Medicina', 'Biologia'], createdAt: 1740000000310 },

  // --- MINAS GERAIS (MG) - MANTIDOS ---
  { id: 'mg-ufmg', name: 'UFMG - Univ. Federal de Minas Gerais', city: 'Belo Horizonte', state: 'MG', address: 'Av. Antônio Carlos, 6627, Pampulha', type: 'Federal', phone: '(31) 3409-5000', website: 'ufmg.br', courses: ['Bioquímica', 'Biomedicina', 'Farmácia', 'Enfermagem', 'Medicina'], createdAt: 1740000000200 },
  { id: 'mg-puc-bh', name: 'PUC Minas', city: 'Belo Horizonte', state: 'MG', address: 'Av. Dom José Gaspar, 500, Coração Eucarístico', type: 'Privada', phone: '(31) 3319-4444', website: 'pucminas.br', courses: ['Biomedicina', 'Enfermagem', 'Farmácia', 'Medicina'], createdAt: 1740000000201 },
  { id: 'mg-ufu', name: 'UFU - Univ. Federal de Uberlândia', city: 'Uberlândia', state: 'MG', address: 'Av. João Naves de Ávila, 2121, Santa Mônica', type: 'Federal', phone: '(34) 3239-4411', website: 'ufu.br', courses: ['Biomedicina', 'Farmácia', 'Enfermagem', 'Medicina', 'Biotecnologia'], createdAt: 1740000000207 },

  // --- RIO GRANDE DO NORTE (RN) - MANTIDOS ---
  { id: 'rn-ufrn-1', name: 'UFRN (Univ. Federal do RN)', city: 'Natal', state: 'RN', address: 'Campus Universitário, Lagoa Nova, Natal - RN, CEP: 59078-970', type: 'Federal', phone: '(84) 3215-3416', website: 'ufrn.br', courses: ['Bioquímica', 'Biomedicina', 'Farmácia'], createdAt: 1740000000100 },
  { id: 'rn-ufersa-1', name: 'UFERSA (Univ. Fed. Rural do Semi-Árido)', city: 'Mossoró', state: 'RN', address: 'Av. Francisco Mota, 572, Costa e Silva, Mossoró - RN, CEP: 59625-900', type: 'Federal', phone: '(84) 3317-8224', website: 'ufersa.edu.br', courses: ['Biotecnologia', 'Medicina'], createdAt: 1740000000103 },

  // --- REGIÃO NORTE - MANTIDOS ---
  { id: 'am-1', name: 'Universidade Federal do Amazonas (UFAM)', city: 'Manaus', state: 'AM', address: 'Av. Rodrigo Otávio, 6200 - Coroado', type: 'Federal', phone: '(92) 3305-1181', website: 'www.ufam.edu.br', courses: ['Medicina', 'Farmácia', 'Bioquímica'], createdAt: 1740000000004 },
  { id: 'pa-1', name: 'Universidade Federal do Pará (UFPA)', city: 'Belém', state: 'PA', address: 'Rua Augusto Corrêa, 1 - Guamá', type: 'Federal', phone: '(91) 3201-7000', website: 'www.ufpa.br', courses: ['Bioquímica', 'Biotecnologia'], createdAt: 1740000000011 }
];
